services:
  nessus:
    build: 
      context: nessus
      args:
        - USERNAME=${NESSUS_USER:?Please create a .env file with NESSUS_USER}
        - PASSWORD=${NESSUS_PASS:?Please create a .env file with NESSUS_PASS}
        - ACTIVATION_CODE=${NESSUS_ACTIVATION_CODE:?Please create a .env file with NESSUS_ACTIVATION_CODE}
    ports:
      - 8834:8834
    container_name: nessus