services:
  kali-oscp:
    build:
      context: .
      args:
        - USERNAME=${KALI_USERNAME:?Please create a .env file with KALI_USERNAME}
        - PASSWORD=${KALI_PASS:?Please create a .env file with KALI_PASS}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: kali-oscp

    network_mode: host # needed if running openvpn in the container
    privileged: true # needed for systemd

    environment:
      - DISPLAY=host.docker.internal:0

    volumes:
      - ~/shared:/home/kali/shared
      - /tmp/.X11-unix:/tmp/.X11-unix # needed for X11 forwarding