#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#Open Docker, only if is not running
if (! docker ps > /dev/null 2>&1 ); then
    # On Mac OS this would be the terminal command to launch Docker
    open /Applications/Docker.app
    #Wait until Docker daemon is running and has completed initialisation
    while (! docker stats --no-stream ); do
        # Docker takes a few seconds to initialize
        echo "Waiting for Docker to launch..."
        sleep 1
    done
fi

docker-compose -f "${SCRIPT_DIR}/docker-compose.kali.yml" down
docker-compose -f "${SCRIPT_DIR}/docker-compose.kali.yml" build kali-oscp
docker image prune --force